// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlOcRymid44hzCqwSN0md46s6il5kr_1o',
    appId: '1:628223282820:web:2492dbdd2bb30a65bc7cd1',
    messagingSenderId: '628223282820',
    projectId: 'to-do-app-6452d',
    authDomain: 'to-do-app-6452d.firebaseapp.com',
    storageBucket: 'to-do-app-6452d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3xpD_zdFdssBaTNRTdDR8lcpyDhf3a1o',
    appId: '1:628223282820:android:e407f1173fab4125bc7cd1',
    messagingSenderId: '628223282820',
    projectId: 'to-do-app-6452d',
    storageBucket: 'to-do-app-6452d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-QHo39g0vW2pjogI2_RgK1H9_I-8lIfo',
    appId: '1:628223282820:ios:b15696df7849fd1ebc7cd1',
    messagingSenderId: '628223282820',
    projectId: 'to-do-app-6452d',
    storageBucket: 'to-do-app-6452d.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-QHo39g0vW2pjogI2_RgK1H9_I-8lIfo',
    appId: '1:628223282820:ios:83ef113e1f7c4effbc7cd1',
    messagingSenderId: '628223282820',
    projectId: 'to-do-app-6452d',
    storageBucket: 'to-do-app-6452d.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
